Repository damienstanton/dotsync, pull requests merged in 2023-09, with the labels that each got.

#2 Update LICENSE
  LICENSE
Labels: documentation, enhancement

#3 Use GitHub Actions for CI
  .github/workflows/test.yml
  README.md
Labels: enhancement, automation

#4 Added '!' to println message to test git commit.
  src/main.rs
Labels: good first issue
